scrape_configs:
  - job_name: 'otel-collector'
    scrape_interval: 10s
    static_configs:
      - targets: ['otel-collector:8889']
      - targets: ['otel-collector:8888']

  - job_name: sample_fastapi
    scrape_interval: 10s
    static_configs:
     - targets: ['sample_fastapi:8000']

  # https://www.jaegertracing.io/docs/1.30/monitoring/
  - job_name: jaeger
    scrape_interval: 10s
    static_configs:
     - targets: ['jaeger:14269']